dc_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

enterprise:
    resource: "@EnterpriseBundle/Controller/"
    resource: "@EnterpriseBundle/Resources/config/routing.yml"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


